version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester-uv
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            uv venv --python 3.9 /usr/local/share/virtualenvs/tap-bronto
            source /usr/local/share/virtualenvs/tap-bronto/bin/activate
            uv pip install .
      - run:
          name: 'pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-bronto/bin/activate
            uv pip install pylint
            pylint tap_bronto --disable missing-docstring,logging-format-interpolation,no-member,broad-except,too-many-branches,consider-using-f-string,unspecified-encoding,raise-missing-from,line-too-long,fixme,unused-variable,no-else-return,redefined-argument-from-local,wrong-import-order,dangerous-default-value,attribute-defined-outside-init,use-a-generator,too-many-locals,invalid-name,deprecated-method,no-else-break,duplicate-code,no-else-continue,too-many-statements,redefined-builtin,unused-import

workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
